### ISSUE TITLE
`text-encoding` npm package no longer maintained? Do we care?

### ISSUE THREAD

**Issue by jrayback** [WebOfTrust/cesr-ts#6]
Please see [here](https://www.npmjs.com/package/text-encoding) and [here](https://github.com/inexorabletash/text-encoding). Package is no longer being maintained. The last commit to the source code was in 2018. Do we care? I can't seem to find any real better alternative (cursory search). Functionality might be, essentially, static and not an issue. Lack of security patching, etc. might be concerning, however.

**Comment by kentbull** [comment]
The TextEncoder package is now integrated into browsers. See https://github.com/WebOfTrust/signify-ts/pull/134 
It can be dropped in favor of the built-in at this point.

**Comment by jrayback** [comment]
Yeah, looks like in this case it just requires importing TextEncoder and TextDecoder from `node:util` instead of `text-encoding`. I'll fix it.

**Comment by lenkan** [comment]
@jrayback it is actually available on global in node.js and on window in browsers. So you do not need to import anything, it is available in the global namespace. Actually, I do not think it will work in the browser if you import it from node:util. See https://nodejs.org/api/globals.html#textencoder and https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder

**Comment by jrayback** [comment]
OK. Yeah. Thanks. I see now. It doesn't require any import statement at all. Once the main code commit is completed, I'll fast follow-on a small change to close out this issue. Thanks for the help.
