### ISSUE TITLE
Suggest moving away from npm `blake3` package

### ISSUE THREAD

**Issue by jrayback** [WebOfTrust/cesr-ts#7]
The package has only 2,500 weekly downloads, and seems poorly maintained. An alternative to consider is [@noble/hashes](https://www.npmjs.com/package/@noble/hashes), which has 1.7 million weekly downloads, has a much better maintenance record, and is externally audited.

**Comment by AlexAndrei98** [comment]
Hey @jrayback  I played a bit around with the nobles libraries and it looks like there is secp256r1 within [@noble/curves](https://github.com/paulmillr/noble-curves/blob/main/src/p256.ts#L9)

**Comment by AlexAndrei98** [comment]
I found this example of usage of secp256r1 in the did-jwt library [here](https://github.com/decentralized-identity/did-jwt/blob/cd7e0ee3b95017c2d2dfa3c657e53fcb95c35365/src/VerifierAlgorithm.ts#L16)

**Comment by jrayback** [comment]
Oh, wow! Good catch! Thank you @AlexAndrei98 . I think the @noble library will be much better. I'll look at the example you sent through and include the migration to the new library in a PR resolving the other package dependency problems.

**Comment by jrayback** [comment]
@AlexAndrei98 , looks like you've already pushed a PR for this one. Thanks. I'll submit something today to handle the other package deps.

**Comment by AlexAndrei98** [comment]
@jrayback Thank you! Will try to fix the package-lock. I was looking at this while working on #15 .

**Comment by jrayback** [comment]
OK, @AlexAndrei98 , I'm actively working on handling the other packages:
-  `text-encoding` (remove)
-  `urlsafe-base64` (remove in favor of native node.js capability)
-  `ecdsa-secp256r1` (replace with `@noble/curves`)
I hope to have a PR ready for review by tomorrow's dev meeting.

**Comment by jrayback** [comment]
closed by #16
